In [1]:
import numpy as np 



In [2]:
a = np.array([1,2,3], dtype='int32')

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

In [9]:
a.nbytes

12

In [10]:
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a[1,5]

np.int64(13)

In [13]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
a[:, 2]

array([ 3, 10])

In [15]:
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20 
a[:,2] = [1,2]

print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
b = np.array([[[1,2], [3,4]], [[5,6],[7, 8]]])

In [18]:
b[0,1,1]

np.int64(4)

In [19]:
b[:,1,:] = [[9,9],[8,8]]

In [20]:
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
b


array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Intializing different types of arrays

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand(4,2)

array([[0.37754416, 0.93795515],
       [0.71159752, 0.60611527],
       [0.81065851, 0.73728062],
       [0.98437968, 0.29799903]])

In [ ]:
np.random.randint(1,8,size=(3,3))

array([[4, 1, 4],
       [3, 6, 5],
       [6, 1, 5]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array 

arr = np.array([[1, 2, 3]])

r1 = np.repeat(arr, 3, axis=0)

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9 
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100 


In [ ]:
print(a)

[1 2 3]


## Linear Algebra

In [ ]:
a = np.zeros((2,3))
print(a)


b = np.full((3,2), 2)

print(b)


np.matmul(a,b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[2 2]
 [2 2]
 [2 2]]


array([[0., 0.],
       [0., 0.]])

In [ ]:
## Find the determinant 
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)


```## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...```


In [ ]:
stats = np.array([[1,2,3], [4,5,6]])
stats 

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

np.int64(1)

In [ ]:
np.min(stats)

np.int64(1)

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Vertically stacking vectors 

In [ ]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7,  8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Horizontal stack 

In [ ]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))


np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Loading data from a File 

In [21]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [23]:
~(((filedata > 50) & (filedata < 100)))


array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])